application: custom-api-proxy
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: api_proxy.proxy_app

libraries:                                                                      
- name: jinja2
  version: latest
- name: ssl
  version: latest
